### ISSUE TITLE
v0.6.0 crashes on startup

### ISSUE THREAD

**Issue by pserwylo** [retrowars/retrowars#25]
**Describe the bug**
Upon opening v0.6.0 of the app built from F-Droid, it crashes immediately with the following logcat:

```
07-07 13:18:27.438 29137 29137 E AndroidRuntime: FATAL EXCEPTION: main
07-07 13:18:27.438 29137 29137 E AndroidRuntime: Process: com.serwylo.retrowars, PID: 29137
07-07 13:18:27.438 29137 29137 E AndroidRuntime: java.lang.ExceptionInInitializerError
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1264)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3797)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4077)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2458)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8387)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx' for target: Linux, 32-bit
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at com.badlogic.gdx.utils.SharedLibraryLoader.load(Unknown Source:82)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at com.badlogic.gdx.utils.GdxNativesLoader.load(Unknown Source:25)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at com.badlogic.gdx.backends.android.AndroidApplication.<clinit>(Unknown Source:0)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	... 15 more
07-07 13:18:27.438 29137 29137 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.serwylo.retrowars--2YQ84TtOIOhFUYmf_3Vpg==/base.apk"],nativeLibraryDirectories=[/data/app/com.serwylo.retrowars--2YQ84TtOIOhFUYmf_3Vpg==/lib/arm64, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]] couldn't find "libgdx.so"
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1668)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	at com.badlogic.gdx.utils.SharedLibraryLoader.load(Unknown Source:24)
07-07 13:18:27.438 29137 29137 E AndroidRuntime: 	... 17 more
```

**To Reproduce**
1. Download v0.6.0 from F-Droid
2. Launch the app
3. It will not open

**Expected behavior**
App launces as per normal

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Huawei P30 Pro (but likely any device)
 - Android Version: 10
 - Version v0.6.0

**Comment by Dragorane** [comment]
Hi,

I've got the same issue on my OnePlus 7 Pro - android release 11 - Oxygen OS 11.0.1.1.GM21BA

Regards

**Comment by Porrumentzio** [comment]
Same on v0.6.0 from F-Droid, Android 9, Xiaomi Redmi Note 4X

**Comment by pserwylo** [comment]
After some browsing last night, I found [this post on the Unciv issue tracker](https://github.com/yairm210/Unciv/issues/3946#issuecomment-857474194). Wonderful work over there as as always, so I will try to fix it [the same way they have](https://github.com/yairm210/Unciv/pull/4090/files).

**Comment by pserwylo** [comment]
I believe this is fixed on F-Droid now.
